# Model Trial

` Nama: Raden Dissa Shafira`

`Batch: RMT - 019`

Pada file ini akan dilakukan trial model Linear Regression dengan data inference yang akan dibuat sebagai percobaan. File ini merupakan lanjutan dari file utama yakni: cab_price_regression.ipynb

# Import Library

In [1]:
# Import Library

import pickle
import json
import pandas as pd
import numpy as np

# Load Model

In [2]:
# loading file

with open('model_lin_reg.pkl', 'rb') as file_1:
  model_lin_reg = pickle.load(file_1)

with open('model_scalers.pkl', 'rb') as file_2:
  model_scaler = pickle.load(file_2)

with open('model_encoder.pkl','rb') as file_3:
  model_encoder = pickle.load(file_3)

with open('list_num_cols.txt', 'r') as file_4:
  list_num_cols = json.load(file_4)

with open('list_cat_cols.txt', 'r') as file_5:
  list_cat_cols = json.load(file_5)

# Inferencing

In [3]:
# membuat data dummy/ inference dan memasukannya ke dalam dataframe

data_inf = {'cab_type': 'Uber', 'name': 'WAV', 'surge_multiplier': 1.0, 'distance': 0.50,
            'day': 1, 'hour': 11, 'month': 6, 'temperature':27,
            'source': 'West End', 'destination': 'North End', 'short_summary': 'Partly Cloudy'}
data_inf = pd.DataFrame([data_inf])
data_inf

cab_type name  surge_multiplier  distance  day  hour  month  temperature  \
0     Uber  WAV               1.0       0.5    1    11      6           27   

     source destination  short_summary  
0  West End   North End  Partly Cloudy

In [4]:
# split antara data numerikal dan kategorikal
data_inf_num = data_inf[list_num_cols]
data_inf_cat = data_inf[list_cat_cols]
data_inf_num

distance  surge_multiplier
0       0.5               1.0

In [5]:
# memastikan data cat terpisah dan tersaring dengan benar
data_inf_cat

cab_type name
0     Uber  WAV

In [6]:
# feature scaling dan feature encoding

data_inf_num_scaled = model_scaler.transform(data_inf_num)
# memastikan scaler bekerja
data_inf_num_scaled

array([[0.06122449, 0.        ]])

In [7]:
data_inf_cat_encoded = model_encoder.transform(data_inf_cat)
# memastikan encoder bekerja
data_inf_cat_encoded

array([[1, 8]])

In [8]:
# menggabungkan data cat yang sudah di encode dan data num yang sudah di scale
data_inf_final = np.concatenate([data_inf_num_scaled, data_inf_cat_encoded], axis=1)

In [9]:
# prediksi dengan Linear Regression
y_pred_inf = model_lin_reg.predict(data_inf_final)
y_pred_inf

array([10.33935771])

Data inference diprediksi akan memiliki nilai sekitar $10.

In [12]:
# menyertakan nilai evaluasi error dari evaluasi pada model sebelumnya 
RMSE = 5.33
print(f'Interval prediksi dengan standar RMSE: {y_pred_inf - RMSE} -  {y_pred_inf + RMSE}')

Interval prediksi dengan standar RMSE: [5.00935771] -  [15.66935771]


Dengan menggunakan error berdasarkan RMSE (dengan argumen bahwa data yang digunakan merupakan data berbasis harga dan sudah dibersihkan dari *outlier*), maka interval prediksi data adalah kisaran \$5.00 hingga \$15.66.

Dapat diambil kesimpulan bahwa model masih belum bekerja dengan akurat, terlebih sebagai model yang memprediksi harga. Sehingga dapat dilakukan analisis untuk perkembangan lebih lanjut (untuk evaluasi dibicarakan lebih lanjut pada file cab_price_regression
ipynb).